// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSN7NzGj9CVkfJih98YaLaYV0WJnVQd9U',
    appId: '1:1062587633068:android:be110eef50e67003257e09',
    messagingSenderId: '1062587633068',
    projectId: 'ocrion-eda2a',
    storageBucket: 'ocrion-eda2a.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN8f0ViupqecJYuSYpYPaXrHRdH10Gu9M',
    appId: '1:1062587633068:ios:ee7809943046ec9a257e09',
    messagingSenderId: '1062587633068',
    projectId: 'ocrion-eda2a',
    storageBucket: 'ocrion-eda2a.firebasestorage.app',
    iosBundleId: 'com.example.celacantoapp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN8f0ViupqecJYuSYpYPaXrHRdH10Gu9M',
    appId: '1:1062587633068:ios:3c7a6ce3457fd6a0257e09',
    messagingSenderId: '1062587633068',
    projectId: 'ocrion-eda2a',
    storageBucket: 'ocrion-eda2a.firebasestorage.app',
    iosBundleId: 'com.',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCQBbD8ioxKiVFEksvJjoDbFjG9drEILg',
    appId: '1:1062587633068:web:861a927f25e03d97257e09',
    messagingSenderId: '1062587633068',
    projectId: 'ocrion-eda2a',
    authDomain: 'ocrion-eda2a.firebaseapp.com',
    storageBucket: 'ocrion-eda2a.firebasestorage.app',
  );
}
